= Test & Evaluation (T&E) Panel
 
* MIX of Government and Industry
** Intros, then open discussion
* Aim/topic: digital transformation to help T&E
 
Changes in leadership, and even policy!
 
== Panel - Members
 
List  of members (opening comments)
 
1. Dr. Sandra Hobson
2. Chris Collins
3. Mark Kassan Director for Nuke Weapon System (Kirtland) (LED Digital Transformation in AFLCMC)
4. Dr. Paul Acarpio (sp)
* Statistical Analysis -- a BAD word for T&E
5. David ____ - Lockheed Martin - T&E Outreach lead
* IF we can make faster decisions, then we'll get better
6. Chris Carhardt (sp) (Boeing)
 
=== Panel -- Around the room:
1. @Chris Collins: emphasis (link back to his) T&E Continuum
* Needs:
** (1) critical data underpinning in model-based (investment in infrastructure, authoritative)
** (2) IF we are REALLY going to , then ensure that tools (e.g., SysML) have T&E components are integrated
** (3) COntinuity of Modeling and Simulation -- we need to be able to work and build off Missioning Engineering Analysis --> Need Ontology, Dictionary, Schema to enable federation of Systems of Systems
 
2. How are we connecting?
* Currently
** Our current processes WORK -- but are TOO slow!
** ONE test at a time
** Need: Design of Experiments
* A case study of a JOINT rocket launch (too many people to blame, so it’s a perfect case study ;) ) BUT his presented approach -- 50% FEWER tests, but more total tests/data were able to be collected
** MOST engineers don't take stats -- BUT you don't have to teach it ... it's now "just a button" (i.e., they can be shown how to leverage it, and taught it on the backend)
** Maybe we need MORE statistics for engineers…
* We have 10 years to wait for culture changes (look at agile -- 2002 -- but not until 2015)
** UNLESS there's POLICY changes!
** Worst case: "Agile Fog" – “yeah we do Agile..."
* New efforts: There's a small window to implement changes
** some might "want to try it" having done it once, but if missed out twice -- they MIGHT be more motivated to try
*** Industry has the smartest engineers in the world -- WHY NOT leverage it/them?
 
* [Dr. Hobson] Key technology is messaged: Integrated T&E in integration of MBSE with T&E to "shift left"
** in terms of acquisition process
** where can we plug in T&E
* Several initiatives in FY23 (what does it look like, who is doing it, how is T&E doing it?)
** SHIFT from document driven processes to "data" driven processes
** how do we represent the system (when buried in Acq docs -- TEMP, Acq Strat, etc.) from development to OT&E/fielding?
*** Retrospective look: there's a system out there -- with OT&E, and what are the opportunities to introduce Tools and Efficiencies?
*** Dev testing, component testing, subs-system, system -- levels of maturity -- ALL provide information to give insight into performance in operational environments
**** SHAPE the system sooner, than later
*** what are the opportunities to form the next phase of test (more efficiency in characterization and follow-up tests)
** In Model-based engineering?
*** USED TO: 200+ page TEMP (that are a snapshot in time)
**** can be used for YEARS
**** NOT flexible, can't be changed
*** We need underlying architecture to support
**** Databases, Tools, how we use different data (circumstances/info) to build
**** The tools/info are OUT THERE -- but
 
[ ] IS MAC doing this? -- pain points/lessons learned
 
[Chris Collins]
WHERE DO WE SAVE MONEY?
* Investment: in Model-based
* Likely in COST avoidance!
 
[Mark Kassan]
Dr. Roper has been pushing this
*
* define training
* WE NEED the functionals (and have) APAN  -- All partner's access network -- DIGITAL guide
* Brought in vendors to teach the Air Force
** Digital Smart Sessions --
** AFMC -- ENTERPRISE LEVEL! (Define at the )
* There's a Tool/metric to enable analysis/tracking of progress
** Referencing Gov't ARchitectures
** Standards in (or moving towards)
** Efforts on DIDs for MBSE contracts
 
 
[]
Machine Learning and AI are removing explicit need for HPC
* enables Cloud
** FMU FMI's to leverage neural networks that are much less demanding
** Avoid Pain Points
* Use of MBSE
** What tends to happens with SE -- Model gets "Drops on the Floor"
*** We move to the NEXT step, then start over
** T&E can influence the MBSE approach
** T&E has (and NEEDS) models that are usable for test -- which is from Systems Engineers
* HOW do we trust the models? (my words -- ALL MODELS are wrong, some are useful)
** Knowing statistical models
* These models, that ARE TRUSTED, can be used in Live, Virtual, Constructive environments
** HIGHER fidelity
* Convergence of Capability to gives great returns when leveraging
 
[Chris Carhardt]
* T&E has to occur early and often
* Systems Integration Lab (hardware-in-the-loop-lab)
** Integrated VM's to FULL "Iron Bird" (everything is real -- except for environment)
** These environments exist on a spectrum
* They can be used ACROSS lifecycle (the "whole V")
** REquirement definition
** To incident/investigation
* Enables iterative development
** Find Emergent behavior that might not have been found in pure analysis or even simulation
** Examples: Cockpit layout/(TO) Process review
*** This gives a setup of "real instances" -- and "simulate everything else"
* How does this address confidence:
** Resilience and REdundancy testing -- this is "as real as you can get" without having a safety issue
*** ex: emergency procedures
*** TOO dangerous to test (e.g., wind shear)
*** MULTIPLE critical issues/failures
 
== Panel Lead Questions
 
Number 1 development:
* Cooperative but sharing can be accomplished, and that pressure can
 
[Chris Collins]
* REsolve as a community: (1) we will NEVER just have 1 approach to solve everything (sysml, cameo, rhapsody)
** underlying data is key
** Onesize fits all (won't work)
 
[Paul A.]
* We are STILL going through the culture change for T&E
** we need to lower barrier of entry
*** Example: it's a HEAVY LIFT to get a tester to use cameo
** Leverage Look at Formula 1 -- they incorporate EVERY LAP of the race -- can we do that?
 
[Dr. Hobson] What efforts are underway for Test & Dev
* Looking at Digital Transformation (many see it as a buzzword) -- so what is meant?
** Education is needed
** Get use cases to show DE and Digital Transformation
* FEAR: model-based environment -- it's NOT as credible
** "Data is data" -- but it's not open air, or hardware in the loop
** There's a lot of angst / level of uncomfort WITHOUT knowing
* There's a struggle for defining "what is confidence level" of representing the truth (the environment, the system)
** V&V -- defining that
** Fidelity of models (and purpose) -- especially with OT&E
* LOTS of issues with transition into this world; and we NEED to be mindful of representing threats, operating environments
** When we NEED to use it for operational environment -- there are DIFFERENT standards, live within the means of what is possible
*** know what we have and don't have
*** know what we "know and don't know"
** Careful and work together to help understand this environment
 
[Chris Collins]
* this approach will INFORM the discussion
* THIS CANNOT be SE modeling, THEN T&E Modeling -- it needs collaboration and agreement
** To enable broader systems-of-systems testing
 
[Mark Kassan]
Question with data intensive work -- how to we determine what data elements are critical
* We have Software and System Architectures
* We can have REALLY good Modelers and really good testers -- but often then don't connect
** Systems and Software engineers
 
* I need this data to answer that question
 
[Chris Carhardt]
* On architecture
* example: look at Mission critical faults -- know gaps (e.g., safety critical analysis events)
** The modeling is needed -- and that drives to data elements
** done at the right
 
[Dr. Paul A.]
How to transform our procurement process?
* Acceptance of artifacts
** MVP of deliverables
** Old: 500 page report... new: if agile process, then we can have incremental delivery and even a model is delivered
 
{Random thought: Documents/Diagrams as code}
 
== Open Questions from Slido Polls/voting (Q&A Session)
 
QUESTION: When is ______
 
"Fully eliminate concept of the document"
* Document could be a view of an underlying model
** this can provide particulars (data/analysis/etc.)
* Do you need ALL stakeholders to speak
INCOSE conference quote: DON'T show your SysML to a city planner -- they'll show you the door
* MBSE is NOT incompatible with documents
Cathedral in a Bazar -- you build a PERFECT model that can used for decades -- but it might not be applicable in every case(vs. interoperability standards)((see Amazon communication via API's only))
 
 
QUESTION: What are the most important (#1 or #2) for DoD
* Engineers are very smart -- but if the policy is pushing us
** Fallacy: I need to be "good at _____" (sysml, process, etc.) --  but you need to be fully expert in all
*** if enforced
 
[Paul A.]
* NEED reference architecture!
** Gov't needs to define this!! (e.g., what data, what is the digital twin) -- and give it
[Mark Kassan]
* You are running TOO slow, when the new-hires are leading your company
[Paul A]
* Model validation -- need a method to accredit/validate the output
[Mark Kassan]
** Perceived Risk: people are threatening that the industry will NOT accept the accreditation
*** Experts need to know how to 'put it together'
 
[Chris Collins]
The gov't does NOT incentivise (and we CANNOT do it piecemeal!)
** ensure resources and can accommodate the failures
 
[Paul A.]
Pre-prepared -- question: MBSE is enabling software, and these are embedded modules
Leverage what has been built, to leverage it in the model, which
NOT everything is modelable -- BUT the parametric data can be captured!
 
[Mark Kassan]
Basic of agile -- are all the skills on the team?
* e.g., you need AI POC -- what level? (Took a class, is a SME/Expert in Industry)
** Put the expert on the team -- everyone learns
 
[Chris Collins]
Evolving and Adapting systems:
production to a point, then
Systems that are deployed -- how to collect data? How to pull back from system to gather new data? Training events as means to gather data?
 
QUESTION: Workforce Development?
Industry and Academia
[David ]
NWC -- few problems and methods to address digital transformation -- there's a LARGE quantity of people that "this way has always worked" (<--- TARGET of education, to improve efficiency and delivery of capes to the warfighter)
** Solution involves people at a CENTER
** NOT A ONE and done -- it has to be continuous (get the early adopters, then the "wait and see" people -- to help build momentum)
* Need to build education -- for tools and w/ Industry
** need enterprise from AFMC
 
[Dr. Hobson]
DoD Workforce Initiatives
* Getting survey completed to ID what we have/what we know -- to drive/ID needs for education and opportunities to "get up to speed"
* ID what they are getting/what is needed
